github_url = "https://github.com/your-tools/ruplacer"

[version]
current = "0.9.0"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Cargo.toml"

[[file]]
src = "README.md"
search = "releases/tag/v{current_version}"


[[before_commit]]
name = "run tests"
cmd = "cargo test"

[[before_commit]]
name = "check changelog"
cmd = "grep {new_version} CHANGELOG.md"

[[before_commit]]
name = "run semver checks"
cmd = "cargo semver-checks"

[[after_push]]
name = "publish"
cmd = "cargo publish"
